name: proprieto-production
services:
  frontend:
    container_name: proprieto-frontend-prod
    image: ghcr.io/quentindrms/proprieto-frontend:latest
    ports:
      - ${FRONTEND_PORT:-3000}:3000
    environment:
      - NODE_ENV=production
    networks:
      - frontback
    restart: always

  backend:
    container_name: proprieto-backend-prod
    image: ghcr.io/quentindrms/proprieto-backend:latest
    ports:
      - ${BACKEND_PORT:-4000}:4000
    environment:
      - NODE_ENV=production
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - database
      - frontback
    restart: always

  postgres:
    image: postgres:18-alpine
    container_name: proprieto-database-prod
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - database
    restart: always

volumes:
  postgres_data:

networks:
  database:
    driver: bridge
  frontback:
    driver: bridge
